// Spin & Solve puzzles: [category, answer].
export const PUZZLES = [
  ['Phrase', 'BREAK A LEG'], ['Phrase', 'PIECE OF CAKE'], ['Phrase', 'ONCE IN A BLUE MOON'], ['Phrase', 'BETTER LATE THAN NEVER'],
  ['Phrase', 'THE BALL IS IN YOUR COURT'], ['Phrase', 'HIT THE NAIL ON THE HEAD'], ['Phrase', 'SPILL THE BEANS'], ['Phrase', 'UNDER THE WEATHER'],
  ['Phrase', 'COST AN ARM AND A LEG'], ['Phrase', 'BITE OFF MORE THAN YOU CAN CHEW'], ['Phrase', 'EVERY CLOUD HAS A SILVER LINING'], ['Phrase', 'ACTIONS SPEAK LOUDER THAN WORDS'],
  ['Phrase', 'THE EARLY BIRD CATCHES THE WORM'], ['Phrase', 'DON’T COUNT YOUR CHICKENS'], ['Phrase', 'WHEN PIGS FLY'], ['Phrase', 'LET THE CAT OUT OF THE BAG'],
  ['Phrase', 'BACK TO SQUARE ONE'], ['Phrase', 'HOME SWEET HOME'], ['Phrase', 'TIME FLIES WHEN YOU’RE HAVING FUN'], ['Phrase', 'PRACTICE MAKES PERFECT'],
  ['Phrase', 'ON CLOUD NINE'], ['Phrase', 'ALL’S WELL THAT ENDS WELL'], ['Phrase', 'A PENNY FOR YOUR THOUGHTS'], ['Phrase', 'BURNING THE MIDNIGHT OIL'],
  ['Food & Drink', 'CHOCOLATE CHIP COOKIES'], ['Food & Drink', 'SPAGHETTI AND MEATBALLS'], ['Food & Drink', 'PEANUT BUTTER AND JELLY'], ['Food & Drink', 'FRESHLY SQUEEZED ORANGE JUICE'],
  ['Food & Drink', 'GRILLED CHEESE SANDWICH'], ['Food & Drink', 'STRAWBERRY SHORTCAKE'], ['Food & Drink', 'HOT CHOCOLATE WITH MARSHMALLOWS'], ['Food & Drink', 'BLUEBERRY PANCAKES'],
  ['Food & Drink', 'CHICKEN NOODLE SOUP'], ['Food & Drink', 'BUTTERED POPCORN'], ['Food & Drink', 'PEPPERONI PIZZA'], ['Food & Drink', 'APPLE PIE A LA MODE'],
  ['Place', 'THE GRAND CANYON'], ['Place', 'NIAGARA FALLS'], ['Place', 'THE EIFFEL TOWER'], ['Place', 'THE GREAT WALL OF CHINA'],
  ['Place', 'MOUNT EVEREST'], ['Place', 'THE AMAZON RAINFOREST'], ['Place', 'THE NORTH POLE'], ['Place', 'A HAUNTED HOUSE'],
  ['Place', 'THE PUBLIC LIBRARY'], ['Place', 'AN AMUSEMENT PARK'], ['Place', 'THE BACK SEAT OF A CAR'], ['Place', 'A TROPICAL ISLAND'],
  ['Thing', 'A ROLL OF DUCT TAPE'], ['Thing', 'BIRTHDAY CANDLES'], ['Thing', 'A PAIR OF SUNGLASSES'], ['Thing', 'THE REMOTE CONTROL'],
  ['Thing', 'A FOUR LEAF CLOVER'], ['Thing', 'A MESSAGE IN A BOTTLE'], ['Thing', 'WIND CHIMES'], ['Thing', 'A TREASURE MAP'],
  ['Thing', 'A ROCKING CHAIR'], ['Thing', 'A SNOW GLOBE'], ['Thing', 'A HOT AIR BALLOON'], ['Thing', 'A GRANDFATHER CLOCK'],
  ['Things', 'FIREWORKS AND SPARKLERS'], ['Things', 'BUCKETS AND SPADES'], ['Things', 'SALT AND PEPPER'], ['Things', 'BATS AND BALLS'],
  ['Things', 'LOOSE CHANGE'], ['Things', 'HOLIDAY DECORATIONS'], ['Things', 'BUBBLES'], ['Things', 'ROLLER SKATES'],
  ['Event', 'A SURPRISE PARTY'], ['Event', 'THE FIRST DAY OF SCHOOL'], ['Event', 'A FAMILY REUNION'], ['Event', 'A TOTAL SOLAR ECLIPSE'],
  ['Event', 'NEW YEAR’S EVE'], ['Event', 'A BACKYARD BARBECUE'], ['Event', 'A WEDDING RECEPTION'], ['Event', 'THE COUNTY FAIR'],
  ['What Are You Doing?', 'BUILDING A SANDCASTLE'], ['What Are You Doing?', 'WALKING THE DOG'], ['What Are You Doing?', 'BAKING BREAD'], ['What Are You Doing?', 'TAKING A NAP'],
  ['What Are You Doing?', 'SINGING IN THE SHOWER'], ['What Are You Doing?', 'PLANTING A GARDEN'], ['What Are You Doing?', 'FLYING A KITE'], ['What Are You Doing?', 'ROASTING MARSHMALLOWS'],
  ['What Are You Doing?', 'JUMPING ON THE TRAMPOLINE'], ['What Are You Doing?', 'WATCHING THE SUNSET'], ['What Are You Doing?', 'PLAYING HIDE AND SEEK'], ['What Are You Doing?', 'ICE SKATING ON A FROZEN POND'],
  ['Occupation', 'MARINE BIOLOGIST'], ['Occupation', 'FIREFIGHTER'], ['Occupation', 'ROCKET SCIENTIST'], ['Occupation', 'PASTRY CHEF'],
  ['Occupation', 'AIR TRAFFIC CONTROLLER'], ['Occupation', 'ZOOKEEPER'], ['Occupation', 'PROFESSIONAL DOG WALKER'], ['Occupation', 'LIGHTHOUSE KEEPER'],
  ['Living Thing', 'A GOLDEN RETRIEVER'], ['Living Thing', 'A HUMMINGBIRD'], ['Living Thing', 'A GIANT PANDA'], ['Living Thing', 'SUNFLOWERS'],
  ['Living Thing', 'A HAMMERHEAD SHARK'], ['Living Thing', 'A BALD EAGLE'], ['Living Thing', 'A VENUS FLYTRAP'], ['Living Thing', 'A POLAR BEAR'],
];
