// Top Answers surveys: a question and its most popular answers with their points (out of 100,
// from our own panel). After the points come other ways people might type the same answer.
export const SURVEYS = [
  ['Name something people do right after waking up', [['Check their phone', 30, 'phone', 'look at phone'], ['Use the bathroom', 22, 'pee', 'toilet', 'bathroom'], ['Brush teeth', 15, 'teeth'], ['Make coffee', 12, 'coffee'], ['Stretch', 8, 'yawn'], ['Shower', 7, 'take a shower']]],
  ['Name a fruit that’s yellow', [['Banana', 48], ['Lemon', 25], ['Pineapple', 11], ['Mango', 6], ['Apple', 4, 'yellow apple'], ['Pear', 3]]],
  ['Name something you find at the beach', [['Sand', 32], ['Shells', 20, 'seashell', 'seashells'], ['Water', 14, 'ocean', 'sea', 'waves'], ['Towel', 10, 'beach towel'], ['Umbrella', 9, 'beach umbrella'], ['Seagull', 7, 'seagulls', 'birds']]],
  ['Name a pet that lives in a cage', [['Hamster', 35], ['Bird', 28, 'parrot', 'budgie', 'parakeet'], ['Guinea pig', 14], ['Rabbit', 10, 'bunny'], ['Mouse', 6, 'mice'], ['Gerbil', 4]]],
  ['Name something people are afraid of', [['Spiders', 30, 'spider'], ['Heights', 22], ['Snakes', 18, 'snake'], ['The dark', 12, 'dark'], ['Clowns', 8, 'clown'], ['Dying', 5, 'death']]],
  ['Name a reason you might be late for work', [['Traffic', 40], ['Overslept', 25, 'slept in', 'alarm', 'woke up late'], ['Car trouble', 14, 'car broke down', 'flat tire'], ['Kids', 9, 'children'], ['Weather', 6, 'snow', 'rain'], ['Bus was late', 4, 'train', 'bus']]],
  ['Name a pizza topping', [['Pepperoni', 38], ['Mushrooms', 18, 'mushroom'], ['Cheese', 12, 'extra cheese'], ['Sausage', 10], ['Onions', 8, 'onion'], ['Pineapple', 7], ['Olives', 4, 'olive']]],
  ['Name something you take on a camping trip', [['Tent', 36], ['Sleeping bag', 22], ['Flashlight', 13, 'torch'], ['Food', 10, 'marshmallows', 'snacks'], ['Bug spray', 7], ['Matches', 6, 'lighter']]],
  ['Name a sport played with a ball', [['Soccer', 28, 'football'], ['Basketball', 25], ['Baseball', 18], ['Tennis', 12], ['Volleyball', 8], ['Golf', 6]]],
  ['Name something people put on a hot dog', [['Ketchup', 35], ['Mustard', 32], ['Relish', 14], ['Onions', 10, 'onion'], ['Chili', 5], ['Sauerkraut', 3]]],
  ['Name a room in a house', [['Kitchen', 30], ['Bedroom', 26], ['Bathroom', 20], ['Living room', 15, 'lounge', 'family room'], ['Dining room', 5], ['Basement', 4]]],
  ['Name something that has wheels', [['Car', 40], ['Bike', 22, 'bicycle'], ['Skateboard', 10], ['Truck', 10], ['Bus', 8], ['Wagon', 5, 'stroller']]],
  ['Name something you do at a birthday party', [['Eat cake', 38, 'cake'], ['Open presents', 22, 'gifts', 'presents'], ['Sing', 18, 'sing happy birthday'], ['Play games', 10, 'games'], ['Blow out candles', 8, 'candles'], ['Dance', 4]]],
  ['Name an animal with stripes', [['Zebra', 52], ['Tiger', 32], ['Skunk', 6], ['Bee', 4], ['Raccoon', 3], ['Chipmunk', 3]]],
  ['Name something you’d find in a junk drawer', [['Batteries', 24, 'battery'], ['Pens', 20, 'pen', 'pencils'], ['Rubber bands', 15, 'elastic bands'], ['Tape', 12], ['Keys', 10, 'key'], ['Scissors', 8]]],
  ['Name a word that rhymes with “cat”', [['Hat', 35], ['Bat', 25], ['Rat', 15], ['Mat', 10], ['Sat', 8], ['Fat', 4]]],
  ['Name something people are always losing', [['Keys', 45], ['Phone', 20], ['Socks', 10, 'sock'], ['Remote', 9, 'tv remote'], ['Glasses', 8, 'sunglasses'], ['Wallet', 6]]],
  ['Name something that’s cold', [['Ice', 38], ['Snow', 22], ['Ice cream', 15], ['Fridge', 10, 'refrigerator', 'freezer'], ['Winter', 7], ['Ice cubes', 5]]],
  ['Name a breakfast food', [['Eggs', 32, 'egg'], ['Pancakes', 22, 'pancake'], ['Cereal', 18], ['Bacon', 12], ['Toast', 8], ['Waffles', 5, 'waffle']]],
  ['Name something you might see on a farm', [['Cow', 32, 'cows'], ['Pig', 18, 'pigs'], ['Horse', 14, 'horses'], ['Tractor', 12], ['Chicken', 10, 'chickens', 'hens'], ['Barn', 8]]],
  ['Name a job where you wear a uniform', [['Police officer', 34, 'police', 'cop'], ['Nurse', 18], ['Firefighter', 15, 'fireman'], ['Soldier', 12, 'military', 'army'], ['Doctor', 9], ['Pilot', 6]]],
  ['Name something you plug in', [['Phone charger', 30, 'charger', 'phone'], ['TV', 22, 'television'], ['Lamp', 15], ['Computer', 12, 'laptop'], ['Toaster', 8], ['Hair dryer', 6]]],
  ['Name a holiday people decorate for', [['Christmas', 55], ['Halloween', 25], ['Easter', 8], ['Thanksgiving', 5], ['Valentine’s Day', 4, 'valentines'], ['New Year', 2, 'new years']]],
  ['Name something people do at the gym', [['Lift weights', 34, 'weights', 'lift'], ['Run', 24, 'treadmill', 'jog'], ['Swim', 10], ['Sweat', 9], ['Stretch', 8, 'yoga'], ['Bike', 7, 'cycle', 'spin']]],
  ['Name something kids hate eating', [['Broccoli', 34], ['Spinach', 18], ['Brussels sprouts', 15, 'sprouts'], ['Peas', 10], ['Liver', 8], ['Carrots', 5, 'vegetables']]],
  ['Name a famous ship', [['Titanic', 60], ['Mayflower', 12], ['Noah’s Ark', 10, 'ark'], ['Santa Maria', 6], ['Black Pearl', 4], ['Queen Mary', 3]]],
  ['Name something you see at a wedding', [['Bride', 30], ['Cake', 22, 'wedding cake'], ['Rings', 15, 'ring'], ['Flowers', 12], ['Dress', 10, 'wedding dress'], ['Groom', 6]]],
  ['Name something you do when you can’t sleep', [['Count sheep', 30, 'sheep'], ['Read', 22, 'read a book'], ['Watch TV', 18, 'tv'], ['Drink milk', 10, 'warm milk'], ['Look at phone', 10, 'phone'], ['Toss and turn', 5]]],
  ['Name a musical instrument', [['Piano', 32], ['Guitar', 30], ['Drums', 14, 'drum'], ['Violin', 10], ['Trumpet', 6], ['Flute', 5]]],
  ['Name something in a first aid kit', [['Bandages', 46, 'band aids', 'plasters', 'bandage'], ['Gauze', 12], ['Ointment', 10, 'cream', 'antiseptic'], ['Tape', 10, 'medical tape'], ['Scissors', 8], ['Gloves', 6]]],
  ['Name something that flies', [['Bird', 36, 'birds'], ['Airplane', 30, 'plane'], ['Helicopter', 10], ['Kite', 8], ['Bee', 6, 'bug', 'insect'], ['Bat', 4]]],
  ['Name a reason people go to the doctor', [['Sick', 34, 'illness', 'flu', 'cold'], ['Checkup', 25, 'physical'], ['Pain', 14, 'hurt'], ['Injury', 10, 'broken bone'], ['Shots', 8, 'vaccine', 'vaccination'], ['Prescription', 5, 'medicine']]],
  ['Name something people put in their coffee', [['Sugar', 38], ['Cream', 28, 'creamer'], ['Milk', 22], ['Sweetener', 5], ['Cinnamon', 3], ['Ice', 2]]],
  ['Name something you find in a classroom', [['Desks', 30, 'desk'], ['Chalkboard', 20, 'whiteboard', 'board'], ['Teacher', 18], ['Books', 12, 'book'], ['Chairs', 8, 'chair'], ['Pencils', 6, 'pencil']]],
  ['Name something associated with a vampire', [['Blood', 35], ['Fangs', 25, 'teeth'], ['Cape', 12], ['Coffin', 10], ['Bats', 8, 'bat'], ['Garlic', 6]]],
  ['Name something you’d do on a rainy day', [['Watch movies', 32, 'movie', 'tv'], ['Read', 20], ['Sleep', 15, 'nap'], ['Play games', 12, 'board games'], ['Stay inside', 10, 'stay home'], ['Bake', 5, 'cook']]],
  ['Name something people collect', [['Stamps', 30], ['Coins', 26], ['Cards', 14, 'baseball cards', 'trading cards'], ['Shells', 8], ['Dolls', 7], ['Rocks', 6]]],
  ['Name a fast food item', [['Burger', 40, 'hamburger', 'cheeseburger'], ['Fries', 30, 'french fries'], ['Chicken nuggets', 12, 'nuggets'], ['Pizza', 8], ['Hot dog', 5], ['Taco', 3]]],
  ['Name something that’s hard to do with your eyes closed', [['Walk', 30], ['Drive', 28], ['Read', 15], ['Write', 10], ['Cook', 8], ['Put on makeup', 5, 'makeup']]],
  ['Name a superhero', [['Superman', 36], ['Batman', 30], ['Spider-Man', 18, 'spiderman'], ['Wonder Woman', 8], ['Hulk', 4], ['Iron Man', 3]]],
  ['Name a place where you have to be quiet', [['Library', 55], ['Church', 15], ['Hospital', 10], ['Movie theater', 8, 'cinema', 'movies'], ['Classroom', 6, 'school'], ['Funeral', 4]]],
  ['Name something you wear on your feet', [['Shoes', 38], ['Socks', 30], ['Boots', 12], ['Sandals', 10, 'flip flops'], ['Slippers', 6], ['Sneakers', 4, 'trainers']]],
];
