// Trivia for Trivia Wheel and Answer Board: six categories, each question as
// [question, right answer, wrong, wrong, wrong, difficulty 1–3].
export const CATS = [
  { id: 'geo', name: 'Geography', color: '#3b82d6', icon: '🌍' },
  { id: 'ent', name: 'Entertainment', color: '#e0559a', icon: '🎬' },
  { id: 'his', name: 'History', color: '#e8b923', icon: '📜' },
  { id: 'art', name: 'Arts & Words', color: '#9a6a3a', icon: '🎨' },
  { id: 'sci', name: 'Science & Nature', color: '#3aa856', icon: '🔬' },
  { id: 'spo', name: 'Sports & Leisure', color: '#ee7a2a', icon: '⚽' },
];
export const Q = {
  geo: [
    ['What is the largest ocean on Earth?', 'Pacific', 'Atlantic', 'Indian', 'Arctic', 1],
    ['What is the capital of France?', 'Paris', 'Lyon', 'Marseille', 'Nice', 1],
    ['Which is the longest river in South America?', 'Amazon', 'Paraná', 'Orinoco', 'Magdalena', 1],
    ['Which continent is Egypt in?', 'Africa', 'Asia', 'Europe', 'Oceania', 1],
    ['What is the capital of Japan?', 'Tokyo', 'Kyoto', 'Osaka', 'Hiroshima', 1],
    ['Which country is shaped like a boot?', 'Italy', 'Greece', 'Portugal', 'Chile', 1],
    ['What is the tallest mountain in the world?', 'Mount Everest', 'K2', 'Kilimanjaro', 'Mont Blanc', 1],
    ['Which US state is made up entirely of islands?', 'Hawaii', 'Alaska', 'Florida', 'Rhode Island', 1],
    ['What is the capital of Australia?', 'Canberra', 'Sydney', 'Melbourne', 'Perth', 2],
    ['Which desert is the largest hot desert in the world?', 'Sahara', 'Gobi', 'Kalahari', 'Mojave', 2],
    ['Which country has the most people?', 'India', 'China', 'United States', 'Indonesia', 2],
    ['What is the capital of Canada?', 'Ottawa', 'Toronto', 'Vancouver', 'Montreal', 2],
    ['The Andes mountains run along which continent?', 'South America', 'Africa', 'Asia', 'North America', 2],
    ['Which European city is built on more than 100 small islands linked by bridges?', 'Venice', 'Amsterdam', 'Copenhagen', 'Stockholm', 2],
    ['Which country has the longest coastline?', 'Canada', 'Russia', 'Australia', 'Norway', 2],
    ['What is the smallest country in the world?', 'Vatican City', 'Monaco', 'San Marino', 'Liechtenstein', 2],
    ['Lake Titicaca sits on the border of Peru and which other country?', 'Bolivia', 'Chile', 'Ecuador', 'Brazil', 3],
    ['What is the capital of Mongolia?', 'Ulaanbaatar', 'Astana', 'Bishkek', 'Tashkent', 3],
    ['Which African country was formerly called Abyssinia?', 'Ethiopia', 'Somalia', 'Kenya', 'Sudan', 3],
    ['What is the deepest lake in the world?', 'Lake Baikal', 'Lake Superior', 'Lake Tanganyika', 'Caspian Sea', 3],
    ['Which country has the most time zones (including overseas territories)?', 'France', 'Russia', 'United States', 'China', 3],
    ['The Strait of Gibraltar separates Spain from which country?', 'Morocco', 'Algeria', 'Tunisia', 'Portugal', 3],
    ['What is the capital of New Zealand?', 'Wellington', 'Auckland', 'Christchurch', 'Queenstown', 2],
    ['Which river flows through London?', 'Thames', 'Seine', 'Severn', 'Avon', 1],
    ['Mount Kilimanjaro is in which country?', 'Tanzania', 'Kenya', 'Uganda', 'Ethiopia', 2],
  ],
  ent: [
    ['In the fairy tale, what does Cinderella lose at the ball?', 'A glass slipper', 'A crown', 'A necklace', 'A glove', 1],
    ['How many strings does a standard guitar have?', 'Six', 'Four', 'Five', 'Eight', 1],
    ['What kind of animal is Winnie-the-Pooh?', 'A bear', 'A pig', 'A rabbit', 'A tiger', 1],
    ['What colour do you get by mixing blue and yellow paint?', 'Green', 'Purple', 'Orange', 'Brown', 1],
    ['Which instrument has 88 keys?', 'Piano', 'Organ', 'Accordion', 'Harp', 1],
    ['In the story, what did Jack trade for magic beans?', 'A cow', 'A goat', 'A horse', 'A hen', 1],
    ['What is the name of the toy cowboy in the first fully computer-animated feature film?', 'Woody', 'Buzz', 'Jessie', 'Andy', 1],
    ['Which fictional detective lived at 221B Baker Street?', 'Sherlock Holmes', 'Hercule Poirot', 'Miss Marple', 'Philip Marlowe', 1],
    ['Which band sang “Hey Jude” and “Let It Be”?', 'The Beatles', 'The Rolling Stones', 'Queen', 'The Who', 2],
    ['In “The Wizard of Oz”, what colour are Dorothy’s slippers in the 1939 film?', 'Ruby red', 'Silver', 'Gold', 'Emerald green', 2],
    ['Which composer wrote the “Moonlight Sonata”?', 'Beethoven', 'Mozart', 'Bach', 'Chopin', 2],
    ['How many musicians are in a quartet?', 'Four', 'Three', 'Five', 'Six', 1],
    ['Who is known as the “King of Pop”?', 'Michael Jackson', 'Elvis Presley', 'Prince', 'Justin Timberlake', 2],
    ['Who is known as the “King of Rock and Roll”?', 'Elvis Presley', 'Chuck Berry', 'Little Richard', 'Buddy Holly', 2],
    ['Which movie features a shark terrorising the town of Amity Island?', 'Jaws', 'The Abyss', 'Deep Blue Sea', 'The Meg', 2],
    ['What is the highest-pitched voice type in a traditional choir?', 'Soprano', 'Alto', 'Tenor', 'Bass', 2],
    ['In which city is the famous opera house with sail-shaped roofs?', 'Sydney', 'Vienna', 'Milan', 'Paris', 2],
    ['Which film won the first Academy Award for Best Picture (1929)?', 'Wings', 'Sunrise', 'The Jazz Singer', 'Metropolis', 3],
    ['Which ballet features the Dance of the Sugar Plum Fairy?', 'The Nutcracker', 'Swan Lake', 'Giselle', 'Coppélia', 2],
    ['How many symphonies did Beethoven complete?', 'Nine', 'Seven', 'Twelve', 'Five', 3],
    ['Which Italian city is the setting of “Romeo and Juliet”?', 'Verona', 'Venice', 'Florence', 'Rome', 3],
    ['Which instrument did jazz legend Louis Armstrong famously play?', 'Trumpet', 'Saxophone', 'Clarinet', 'Trombone', 2],
    ['What is the name of the hobbit who carries the One Ring to Mordor?', 'Frodo', 'Bilbo', 'Sam', 'Pippin', 2],
    ['Which classic film has the line “Here’s looking at you, kid”?', 'Casablanca', 'Gone with the Wind', 'Citizen Kane', 'Vertigo', 3],
    ['Which composer wrote “The Four Seasons”?', 'Vivaldi', 'Handel', 'Haydn', 'Bach', 3],
  ],
  his: [
    ['Who was the first President of the United States?', 'George Washington', 'Abraham Lincoln', 'Thomas Jefferson', 'John Adams', 1],
    ['Which ancient people built the pyramids at Giza?', 'Egyptians', 'Romans', 'Greeks', 'Mayans', 1],
    ['In which year did the Titanic sink?', '1912', '1905', '1921', '1898', 1],
    ['Who was the first person to walk on the Moon?', 'Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'John Glenn', 1],
    ['Which wall fell in 1989, reuniting a divided city?', 'Berlin Wall', 'Great Wall', 'Hadrian’s Wall', 'Western Wall', 1],
    ['What was the name of the ship that carried the Pilgrims to America in 1620?', 'Mayflower', 'Santa Maria', 'Endeavour', 'Beagle', 1],
    ['Which empire was ruled by Julius Caesar?', 'Roman', 'Greek', 'Persian', 'Ottoman', 1],
    ['In which country did the Olympic Games begin?', 'Greece', 'Italy', 'Egypt', 'France', 1],
    ['Who painted the ceiling of the Sistine Chapel?', 'Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello', 2],
    ['In which year did World War II end?', '1945', '1944', '1946', '1918', 2],
    ['Which queen ruled Britain for over 63 years in the 1800s?', 'Victoria', 'Elizabeth I', 'Anne', 'Mary', 2],
    ['Who wrote the Declaration of Independence’s first draft?', 'Thomas Jefferson', 'Benjamin Franklin', 'John Adams', 'George Washington', 2],
    ['Which explorer’s expedition was the first to sail around the world?', 'Ferdinand Magellan', 'Christopher Columbus', 'Vasco da Gama', 'James Cook', 2],
    ['What was the first country to give women the vote nationally (1893)?', 'New Zealand', 'United States', 'Britain', 'Finland', 3],
    ['Which French military leader was exiled to the island of Elba?', 'Napoleon', 'Charlemagne', 'Louis XIV', 'Joan of Arc', 2],
    ['The Great Fire of London happened in which year?', '1666', '1066', '1766', '1566', 3],
    ['Which civilisation built Machu Picchu?', 'Inca', 'Aztec', 'Maya', 'Olmec', 2],
    ['Who was the British Prime Minister for most of World War II?', 'Winston Churchill', 'Neville Chamberlain', 'Clement Attlee', 'Anthony Eden', 2],
    ['Which city was buried by Mount Vesuvius in 79 AD?', 'Pompeii', 'Athens', 'Carthage', 'Troy', 2],
    ['Who was the first emperor of China?', 'Qin Shi Huang', 'Kublai Khan', 'Sun Yat-sen', 'Confucius', 3],
    ['The Magna Carta was signed in which year?', '1215', '1066', '1415', '1314', 3],
    ['Which ancient wonder stood in the harbour of Rhodes?', 'The Colossus', 'The Lighthouse', 'The Hanging Gardens', 'The Mausoleum', 3],
    ['Who invented the printing press with movable type in Europe around 1440?', 'Johannes Gutenberg', 'William Caxton', 'Martin Luther', 'Galileo', 3],
    ['Which two cities were the first and second to be hit by atomic bombs?', 'Hiroshima and Nagasaki', 'Tokyo and Osaka', 'Kyoto and Kobe', 'Nagasaki and Tokyo', 2],
    ['Which US President issued the Emancipation Proclamation?', 'Abraham Lincoln', 'Ulysses S. Grant', 'Andrew Johnson', 'James Buchanan', 2],
  ],
  art: [
    ['Who painted the Mona Lisa?', 'Leonardo da Vinci', 'Michelangelo', 'Rembrandt', 'Van Gogh', 1],
    ['Who wrote “Romeo and Juliet”?', 'William Shakespeare', 'Charles Dickens', 'Jane Austen', 'Mark Twain', 1],
    ['What is the opposite of “ancient”?', 'Modern', 'Old', 'Antique', 'Historic', 1],
    ['How many letters are in the English alphabet?', '26', '24', '25', '28', 1],
    ['What do you call a word that means the same as another word?', 'Synonym', 'Antonym', 'Homonym', 'Acronym', 1],
    ['Which artist cut off part of his own ear?', 'Vincent van Gogh', 'Pablo Picasso', 'Claude Monet', 'Salvador Dalí', 1],
    ['Who wrote “Alice’s Adventures in Wonderland”?', 'Lewis Carroll', 'Roald Dahl', 'C. S. Lewis', 'J. M. Barrie', 2],
    ['What is a haiku?', 'A short Japanese poem', 'A Japanese sword', 'A kind of paper folding', 'A tea ceremony', 1],
    ['Who wrote “Pride and Prejudice”?', 'Jane Austen', 'Charlotte Brontë', 'Emily Brontë', 'George Eliot', 2],
    ['Which artist is famous for melting clocks in “The Persistence of Memory”?', 'Salvador Dalí', 'René Magritte', 'Pablo Picasso', 'Joan Miró', 2],
    ['Which art movement was Pablo Picasso a founder of?', 'Cubism', 'Impressionism', 'Surrealism', 'Pop Art', 2],
    ['In “Moby-Dick”, what is the name of the obsessed captain?', 'Ahab', 'Nemo', 'Hook', 'Queeg', 2],
    ['Who wrote “A Christmas Carol”?', 'Charles Dickens', 'Thomas Hardy', 'Oscar Wilde', 'Robert Louis Stevenson', 2],
    ['What is the plural of “cactus” (one accepted form)?', 'Cacti', 'Cactuses', 'Cactae', 'Cactes', 2],
    ['Which French painter is known for his water lily paintings?', 'Claude Monet', 'Édouard Manet', 'Paul Cézanne', 'Edgar Degas', 2],
    ['Who wrote the novel “1984”?', 'George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'H. G. Wells', 2],
    ['What is a group of words that reads the same backwards called?', 'Palindrome', 'Anagram', 'Acrostic', 'Spoonerism', 2],
    ['Which Dutch painter created “The Night Watch”?', 'Rembrandt', 'Vermeer', 'Van Gogh', 'Bosch', 3],
    ['Who wrote “One Hundred Years of Solitude”?', 'Gabriel García Márquez', 'Isabel Allende', 'Jorge Luis Borges', 'Pablo Neruda', 3],
    ['How many lines does a sonnet traditionally have?', '14', '12', '10', '16', 3],
    ['Who sculpted “The Thinker”?', 'Auguste Rodin', 'Michelangelo', 'Donatello', 'Bernini', 3],
    ['In which country did the haiku form begin?', 'Japan', 'China', 'Korea', 'Vietnam', 2],
    ['Who wrote “The Old Man and the Sea”?', 'Ernest Hemingway', 'John Steinbeck', 'F. Scott Fitzgerald', 'William Faulkner', 3],
    ['Which painter is famous for “The Starry Night”?', 'Vincent van Gogh', 'Paul Gauguin', 'Henri Matisse', 'Georges Seurat', 1],
    ['Who wrote “Frankenstein”?', 'Mary Shelley', 'Bram Stoker', 'Edgar Allan Poe', 'H. P. Lovecraft', 3],
  ],
  sci: [
    ['What planet is known as the Red Planet?', 'Mars', 'Venus', 'Jupiter', 'Mercury', 1],
    ['What gas do plants take in from the air?', 'Carbon dioxide', 'Oxygen', 'Nitrogen', 'Helium', 1],
    ['How many legs does a spider have?', 'Eight', 'Six', 'Ten', 'Twelve', 1],
    ['What is the largest planet in our solar system?', 'Jupiter', 'Saturn', 'Neptune', 'Earth', 1],
    ['What is water made of?', 'Hydrogen and oxygen', 'Carbon and oxygen', 'Nitrogen and hydrogen', 'Salt and oxygen', 1],
    ['What is the largest mammal?', 'Blue whale', 'Elephant', 'Giraffe', 'Hippopotamus', 1],
    ['What is the hardest natural substance?', 'Diamond', 'Gold', 'Iron', 'Quartz', 1],
    ['How many bones are in the adult human body?', '206', '196', '212', '180', 2],
    ['What is the chemical symbol for gold?', 'Au', 'Ag', 'Gd', 'Go', 2],
    ['What is the closest star to Earth?', 'The Sun', 'Proxima Centauri', 'Sirius', 'Polaris', 2],
    ['Which organ pumps blood around the body?', 'Heart', 'Lungs', 'Liver', 'Kidneys', 1],
    ['At what temperature does water boil at sea level in Celsius?', '100°', '90°', '120°', '212°', 1],
    ['What do bees make?', 'Honey', 'Milk', 'Silk', 'Wax only', 1],
    ['Which planet has the most famous rings?', 'Saturn', 'Uranus', 'Jupiter', 'Neptune', 1],
    ['What is the fastest land animal?', 'Cheetah', 'Lion', 'Pronghorn', 'Greyhound', 2],
    ['What part of the cell holds its DNA?', 'Nucleus', 'Membrane', 'Ribosome', 'Cytoplasm', 2],
    ['What is the chemical symbol for sodium?', 'Na', 'So', 'Sd', 'S', 3],
    ['Which blood type is known as the universal donor?', 'O negative', 'AB positive', 'A negative', 'B positive', 3],
    ['What is the most abundant gas in Earth’s atmosphere?', 'Nitrogen', 'Oxygen', 'Carbon dioxide', 'Argon', 2],
    ['How long does light from the Sun take to reach Earth, roughly?', '8 minutes', '8 seconds', '8 hours', '1 minute', 3],
    ['What is a baby kangaroo called?', 'A joey', 'A kit', 'A cub', 'A pup', 2],
    ['Which scientist developed the theory of general relativity?', 'Albert Einstein', 'Isaac Newton', 'Niels Bohr', 'Stephen Hawking', 2],
    ['What is the powerhouse of the cell?', 'Mitochondria', 'Nucleus', 'Golgi body', 'Chloroplast', 2],
    ['What is the smallest planet in our solar system?', 'Mercury', 'Mars', 'Pluto', 'Venus', 3],
    ['What type of animal is a Komodo dragon?', 'A lizard', 'A snake', 'A crocodile', 'A turtle', 2],
  ],
  spo: [
    ['How many players are on a soccer team on the field?', 'Eleven', 'Nine', 'Ten', 'Twelve', 1],
    ['In which sport do you use a shuttlecock?', 'Badminton', 'Tennis', 'Squash', 'Table tennis', 1],
    ['How many points is a touchdown worth in American football?', 'Six', 'Seven', 'Three', 'Five', 1],
    ['What colour is the bullseye on a standard dartboard’s very centre?', 'Red', 'Green', 'Black', 'Yellow', 2],
    ['How many squares are on a chessboard?', '64', '81', '100', '48', 1],
    ['In bowling, what is it called when you knock down all ten pins with your first ball?', 'A strike', 'A spare', 'A split', 'A turkey', 1],
    ['How many holes are played in a standard round of golf?', '18', '9', '12', '21', 1],
    ['Which sport is played at Wimbledon?', 'Tennis', 'Cricket', 'Golf', 'Polo', 1],
    ['How often are the Summer Olympics usually held?', 'Every four years', 'Every two years', 'Every year', 'Every five years', 1],
    ['In which sport would you perform a slam dunk?', 'Basketball', 'Volleyball', 'Handball', 'Water polo', 1],
    ['How many rings are on the Olympic flag?', 'Five', 'Four', 'Six', 'Seven', 1],
    ['What is the maximum score with three darts?', '180', '150', '160', '200', 2],
    ['In which country did the sport of judo originate?', 'Japan', 'China', 'Korea', 'Thailand', 2],
    ['How many players are on a basketball team on the court?', 'Five', 'Six', 'Seven', 'Four', 1],
    ['What is a score of zero called in tennis?', 'Love', 'Nil', 'Duck', 'Blank', 2],
    ['How long is a marathon, roughly?', '42 km (26.2 miles)', '30 km (18.6 miles)', '50 km (31 miles)', '21 km (13.1 miles)', 2],
    ['In cricket, how many balls are in a standard over?', 'Six', 'Five', 'Eight', 'Ten', 2],
    ['Which piece in chess can only move diagonally?', 'Bishop', 'Rook', 'Knight', 'Queen', 2],
    ['In which sport is the Stanley Cup awarded?', 'Ice hockey', 'Baseball', 'Basketball', 'American football', 2],
    ['What is the highest possible break in snooker (without a free ball)?', '147', '155', '140', '180', 3],
    ['How many players are on each side in a rugby union team?', '15', '13', '11', '12', 3],
    ['In which city were the first modern Olympic Games held in 1896?', 'Athens', 'Paris', 'London', 'Rome', 3],
    ['How many dimples does a golf ball typically have, roughly?', 'About 300–500', 'About 50', 'About 1,000', 'About 100', 3],
    ['What is the name for three strikes in a row in bowling?', 'A turkey', 'A hat trick', 'A triple', 'A clean sweep', 3],
    ['In baseball, how many strikes make an out?', 'Three', 'Four', 'Two', 'Five', 1],
  ],
};
