// Real (and really obscure) English words with their real meanings, for Word Bluff.
export const WORDS = [
  ['Absquatulate', 'To leave somewhere suddenly, without saying goodbye'],
  ['Bumfuzzle', 'To confuse or fluster someone'],
  ['Cattywampus', 'Crooked or askew; not lined up properly'],
  ['Collywobbles', 'A nervous, fluttery feeling in the stomach'],
  ['Crapulence', 'The sick feeling after eating or drinking too much'],
  ['Defenestration', 'The act of throwing someone or something out of a window'],
  ['Discombobulate', 'To confuse or disconcert someone'],
  ['Erinaceous', 'Like a hedgehog'],
  ['Flibbertigibbet', 'A silly, flighty person who talks too much'],
  ['Gardyloo', 'A warning shout before throwing dirty water out of a window'],
  ['Gongoozler', 'Someone who idly watches boats on a canal'],
  ['Hornswoggle', 'To cheat or trick someone'],
  ['Kerfuffle', 'A commotion or fuss'],
  ['Lollygag', 'To dawdle or waste time'],
  ['Mumpsimus', 'Someone who sticks to a mistake even after it is pointed out'],
  ['Nudiustertian', 'Relating to the day before yesterday'],
  ['Ombrophobia', 'A fear of rain'],
  ['Pandiculation', 'Stretching and yawning at the same time, as when waking up'],
  ['Quockerwodger', 'A wooden puppet on strings; a politician controlled by others'],
  ['Ratoon', 'A new shoot that grows from the root of a cut plant, like sugar cane'],
  ['Snollygoster', 'A clever, unprincipled person, especially a politician'],
  ['Taradiddle', 'A small lie; pretentious nonsense'],
  ['Ultracrepidarian', 'Someone who gives opinions on things they know nothing about'],
  ['Vomitory', 'An entrance passage through which crowds leave a stadium or theatre'],
  ['Widdershins', 'Counterclockwise; in the opposite direction to the sun'],
  ['Xertz', 'To gulp down quickly and greedily'],
  ['Yarborough', 'A hand in bridge or whist with no card higher than a nine'],
  ['Zugzwang', 'In chess, a position where any move you make will hurt you'],
  ['Agelast', 'Someone who never laughs'],
  ['Bibliopole', 'Someone who buys and sells books, especially rare ones'],
  ['Callipygian', 'Having nicely shaped buttocks'],
  ['Dactylonomy', 'Counting on your fingers'],
  ['Eructation', 'A burp'],
  ['Fard', 'To paint the face with makeup'],
  ['Gobemouche', 'Someone who believes everything they hear'],
  ['Hirsute', 'Hairy'],
  ['Impignorate', 'To pawn or mortgage something'],
  ['Jentacular', 'Relating to breakfast'],
  ['Kakorrhaphiophobia', 'A fear of failure'],
  ['Lethologica', 'Not being able to remember the word you want'],
  ['Mondegreen', 'A misheard song lyric or phrase'],
  ['Nidificate', 'To build a nest'],
  ['Oxter', 'The armpit'],
  ['Petrichor', 'The pleasant smell of rain on dry ground'],
  ['Quomodocunquize', 'To make money in any way possible'],
  ['Rawky', 'Foggy, damp and cold'],
  ['Scurryfunge', 'To hurriedly tidy up before visitors arrive'],
  ['Tittynope', 'A small amount of something left over'],
  ['Uhtceare', 'Lying awake before dawn, worrying'],
  ['Vellichor', 'The strange wistfulness of a used bookshop'],
  ['Wabbit', 'Exhausted or slightly unwell'],
  ['Yex', 'To hiccup'],
  ['Zoanthropy', 'The belief that you have turned into an animal'],
  ['Brabble', 'To argue loudly about something unimportant'],
  ['Cabotage', 'Shipping or flying passengers between two places in the same country'],
  ['Dowsabel', 'A sweetheart'],
  ['Elflock', 'A tangled lock of hair'],
  ['Fogle', 'A silk handkerchief'],
  ['Groak', 'To silently watch someone eat, hoping they will offer you some'],
  ['Hugger-mugger', 'Secrecy; or a confused muddle'],
  ['Jargogle', 'To confuse or jumble'],
  ['Kench', 'To laugh loudly'],
  ['Lunting', 'Walking while smoking a pipe'],
  ['Mubblefubbles', 'A feeling of gloom for no particular reason'],
  ['Nikhedonia', 'The pleasure of looking forward to success'],
  ['Onychophagia', 'The habit of biting your nails'],
  ['Pogonotrophy', 'Growing a beard'],
  ['Quidnunc', 'A nosy person who always wants to know the latest gossip'],
  ['Ruddock', 'A robin'],
  ['Sesquipedalian', 'Using, or being, very long words'],
  ['Tatterdemalion', 'A person in ragged, tattered clothes'],
  ['Ugsome', 'Horrible or disgusting'],
  ['Wamble', 'A rumbling of the stomach'],
  ['Yerk', 'To tie stitches tightly, as a shoemaker does'],
  ['Zenzizenzizenzic', 'A number raised to the eighth power'],
  ['Bloviate', 'To talk at length in a pompous, empty way'],
  ['Cacoethes', 'An irresistible urge to do something unwise'],
  ['Didappers', 'Small diving birds; little grebes'],
  ['Febrifuge', 'A medicine that brings down a fever'],
  ['Gubbins', 'Odds and ends; bits of equipment'],
  ['Inglenook', 'A cosy corner beside a fireplace'],
  ['Jobbernowl', 'A stupid person'],
  ['Lucubrate', 'To study or write late at night by lamplight'],
  ['Philtrum', 'The groove between your nose and upper lip'],
  ['Rigmarole', 'A long, complicated and annoying procedure'],
  ['Snickersnee', 'A large knife, or a fight with knives'],
  ['Tergiversate', 'To keep changing your opinion; to be evasive'],
  ['Vexillology', 'The study of flags'],
];
