// Wrong Number: every text and reply here is written for Play On Display.
// Prompts are texts from an unknown number; replies are what you send back.

export const PROMPTS = [
  'hey it\'s me. from last night. you still have my shoe?',
  'Who is this? Your number was written on my hand when I woke up.',
  'URGENT: the goat is loose again',
  'did you take the leftovers with my name on them',
  'Hi, this is your dentist. We need to talk about what you said under the gas.',
  'grandma just joined the group chat. delete everything.',
  'are we still doing the thing on saturday or did that get weird',
  'I know what you did at the bowling alley.',
  'new phone. lost all my contacts. who are you and how much do I owe you',
  'can you pick me up? don\'t ask why I\'m at the aquarium at 3am',
  'my mom says hi and also that she\'s disappointed',
  'Your package could not be delivered. It is too loud.',
  'quick question: how many raccoons is too many raccoons',
  'I\'m outside.',
  'whatever you do, don\'t open the fridge',
  'is this the guy who sold me the haunted lamp',
  'Congratulations! You\'ve been selected as the new mayor.',
  'pls come get your parrot it learned my wifi password',
  'we need to talk about the karaoke video',
  'Hi! Wrong number but you seem nice. Want to be pen pals?',
  'the cat knocked over the candle. everything\'s fine. mostly.',
  'reminder: your wedding is tomorrow',
  'Hey, I matched with you online. Your profile pic was a potato?',
  'boss wants to see you in his office. bring snacks.',
  'is it weird that I miss the ferret',
  'the landlord found the hot tub',
  'Your Uber driver is outside. He\'s crying.',
  'Thanks for the lovely evening. Who were you?',
  'lol I just saw your dad on the news',
  'Hi, you were my emergency contact. Emergency over. Long story.',
  'u up?',
  'I need you to be my plus one. Don\'t ask questions. Wear a cape.',
  'This is the library. Your book is 11 years overdue.',
  'just found out I\'m adopted. also so is the dog.',
  'can you water my plants while I\'m in witness protection',
  'Dinner\'s ready. Also the smoke alarm is singing.',
  'the twins are at it again',
  'Hey it\'s your neighbor. Why is there a canoe on my roof?',
  'my therapist wants to meet you',
  'So the snake got out.',
  'Please stop sending me pictures of soup.',
  'is this a bad time to tell you I sold your car',
  'Congrats on your promotion! I\'m your new assistant. I\'m 9.',
  'Did you leave a llama in the elevator?',
  'how do I tell my in-laws I\'m a magician',
  'Party at my place. Bring a casserole and a lawyer.',
  'Your horoscope says today is the day. Of what, it won\'t say.',
  'the vending machine took my money and my dignity',
  'My wife found the receipt for the pirate ship.',
  'Hi it\'s your past self. Don\'t eat the gas station sushi.',
  'got a parking ticket in a parking lot. explain.',
  'I need a ride to the airport. And a fake mustache.',
  'Your pizza is on its way! The driver is lost in thought.',
  'just watched you trip from across the street. you ok?',
  'The baby said its first word. It was your name.',
  'hey! it\'s Kevin from the hot air balloon',
  'I accidentally joined a cult. Can you cover my shift?',
  'grandpa is live streaming again',
  'Please return the trophy. You did not win the pie contest.',
  'it happened again. the spoons are gone.',
  'the HOA wants to talk about your lawn flamingos',
  'Just checking you got home safe from the medieval fair',
  'I\'m at your door with a casserole and some bad news.',
  'So about the tattoo.',
  'Hey, are you the person who keeps leaving tiny hats on my car?',
  'Your free trial of adulthood has ended.',
  'My GPS says to drive into the lake. Thoughts?',
  'this is your bank. why did you buy 400 rubber ducks',
  'i think the house is haunted but in a fun way',
  'The wedding band cancelled. Can you play the kazoo?',
];

export const REPLIES = [
  'New phone, who this?',
  'Sorry, I only respond to carrier pigeon.',
  'This is a recording.',
  'Can\'t talk, I\'m in a meeting with myself.',
  'Absolutely not. Also yes.',
  'I\'ll need that in writing. In crayon.',
  'Is this about the llama? Because I was framed.',
  'k',
  'I have no memory of this and I\'d like to keep it that way.',
  'Sending thoughts and prayers and a small amount of cheese.',
  'Per my last email…',
  'My lawyer has advised me to send a thumbs up 👍',
  'We were on a break.',
  'Cool cool cool cool cool.',
  'I\'m legally not allowed within 50 feet of a bowling alley.',
  'Tell my mom I said hi back. And sorry.',
  'This sounds like a problem for future me.',
  'Ok but did you try turning it off and on again?',
  'I am currently in a hot tub. Can\'t elaborate.',
  'Lol same.',
  'That\'s the third time this week.',
  'Wrong number but right energy.',
  'Is this the pizza place? Please say this is the pizza place.',
  'I\'ll be there in 5 business days.',
  'Not my circus. Definitely my monkeys.',
  'I can neither confirm nor deny the raccoons.',
  'Bold of you to assume I own shoes.',
  'Brb, faking my own death.',
  'Thank you for your feedback. It has been ignored.',
  'Is it too late to say sorry?',
  'Mom?',
  'I\'ve been expecting you.',
  'Please hold. Your call is very important to absolutely no one.',
  'Love that for you.',
  'Ugh, fine. But I\'m bringing the accordion.',
  'Sir, this is a laundromat.',
  'Delete this number. Then delete your number.',
  'I\'m going to need a bigger boat.',
  'Can I call you back after my nap? It\'s a long nap.',
  'Respectfully, no.',
  'I knew this day would come.',
  'Ask me again after three margaritas.',
  'Plot twist: I\'m the goat.',
  'Same thing happened to my uncle. He\'s a lighthouse now.',
  'Who gave you this number? Was it Gary?',
  'I\'m 40% sure that was me.',
  'This message will self-destruct in 3… 2…',
  'Sorry, this phone belongs to a dog now.',
  'Ok but what\'s in it for me?',
  'Shhh. They\'re listening.',
  'Big if true.',
  'I\'m on it. By "it" I mean the couch.',
  'Hate when that happens.',
  'Have you tried essential oils?',
  'I\'ll allow it.',
  'You\'re breaking up… ksshhh… tunnel…',
  'That\'s between me and the moon.',
  'Can\'t. Busy being emotionally unavailable.',
  'Spoiler: it gets worse.',
  'I\'m telling Grandma.',
  'Do you know how much glitter that took?',
  'It\'s not a phase, Mom.',
  'This is fine 🔥',
  'Okay, but hear me out: more raccoons.',
  'Already on my way with a shovel.',
  'Don\'t worry, I have a guy.',
  'Weird flex but ok.',
  'Please direct all complaints to my parrot.',
  'Lol you think I can read?',
  'That\'s classified.',
  'I\'m legally changing my name to avoid this conversation.',
  'Put it on my tab.',
  'Let me check with my emotional support lizard.',
  'Yes. The answer is always yes.',
  'Hard pass. Soft maybe.',
  'I\'ll trade you for a sandwich.',
  'Wait, which one of my secret families is this?',
  'You had me at "goat."',
  'That\'s not even my final form.',
  'I\'m in witness protection. Who\'s asking?',
  'Okay but don\'t tell anyone about the trampoline.',
  'Pics or it didn\'t happen.',
  'I\'ve made a terrible mistake.',
  'It was like that when I got here.',
  'Next!',
  'Uh oh. Uh oh. Uh OH.',
  'Fine, but I\'m wearing the cape.',
  'This is why we can\'t have nice things.',
  'I blame the moon.',
  'Hold on, my cat is typing.',
  'Seen 2:14am',
  'Is this a hostage situation? Blink twice.',
  'My horoscope warned me about you.',
  'I only speak in interpretive dance now.',
  'That\'s a Tuesday problem and today\'s Monday.',
  'Not without my llama.',
  'I accept your apology. I don\'t accept the casserole.',
  'You\'re the reason there are instructions on shampoo.',
  'Let\'s just say the ferret knows what it did.',
  'Ok but who\'s bringing snacks?',
  'I object. Strongly. With interpretive dance.',
  'Can\'t talk, being chased by geese.',
  'I need an adult. Wait, I am one. Ugh.',
  'Somebody alert the authorities. Or a llama.',
  'Not me reading this from the roof.',
  'Is there a dress code for this disaster?',
  'I\'ve already told the group chat.',
  'Thanks, I hate it.',
  'Gonna need you to say that in a pirate voice.',
  'Who let you have a phone?',
  'Mood.',
  'I\'m sorry, I don\'t negotiate with toddlers.',
  'The real treasure was the friends we made.',
  'You\'re on speaker. Grandma says hi.',
  'Sending you a voice note of me screaming.',
  'Ok but did you remember to feed the snake?',
  'I can explain. I won\'t, but I could.',
  'Hey, at least it\'s not the spoons again.',
  'Could be worse. Could be raining.',
  'It\'s raining.',
  'Was it the tiny hats? It was the tiny hats.',
  'Bring a helmet.',
  'Please consult my 47-page manifesto.',
  'This is my villain origin story.',
  'I\'m adding this to my memoir.',
  'Only if you say "pretty please with sprinkles."',
  'Running late. Also running away.',
  'Can I get a refund on this conversation?',
  'Just pretend I\'m a fax machine.',
  'Sounds like a group project.',
  'I was told there would be cake.',
  'Do not, under any circumstances, call my mother.',
  'The prophecy is fulfilled.',
  'Correct, but in the worst way.',
  'I knew I should\'ve stayed in bed.',
  'One sec, consulting my Magic 8 Ball. It says "lol no."',
  'Who among us hasn\'t sold a car by accident?',
  'Okay, but in my defense, I was bored.',
  'Fine. I\'ll bring the pirate ship.',
  'I have so many questions and zero follow-ups.',
  'Honestly? Iconic.',
  'Don\'t threaten me with a good time.',
  'Can\'t stop. Won\'t stop. Probably should stop.',
  'Leave a message after the yodel.',
  'Your secret\'s safe with me and 3,000 followers.',
  'We don\'t talk about the kazoo incident.',
  'I\'ve been training my whole life for this.',
  'This is my roman empire now.',
  'Ma\'am, I\'m a horse.',
  'Haha. Wait. Was that real?',
  'Sorry, I had to google "llama lawyer."',
  'Good news: I found your shoe. Bad news: it\'s on the goat.',
  'Same, but with ducks.',
  'Okay, but hypothetically, how much is bail?',
  'Wait, I thought YOU had the baby.',
  'I\'ve been ghosted by better.',
  'Count me in. Count me out. Count me sideways.',
  'Please stop texting this number. It\'s a vending machine.',
  'I am a 401(k) and I feel threatened.',
  'Cool story. Tell it to my cactus.',
  'Have you met my lawyer, Mr. Whiskers?',
  'My spirit animal is a panicked squirrel.',
  'Not again.',
  'I\'m choosing to believe this is a dream.',
  'Fine. FINE. I\'ll wear the mustache.',
  'Yikes on bikes.',
  'Calm down, it\'s only a little haunted.',
  'Absolutely. Who\'s Kevin?',
  'Wow. Just wow. Anyway, how\'s the weather?',
  'That sounds like a you problem with extra steps.',
  'Wait till you hear what the dog did.',
  'I\'ll bring the flamingos.',
  'You had one job.',
  'Now accepting applications for a new best friend.',
  'This text has been forwarded to my therapist.',
  'Respect the hustle.',
  'Unsubscribe.',
];
